### ISSUE TITLE
Camera Not Working 

### ISSUE THREAD

**Issue by ramantehlan** [AmolAmrit/device_xiaomi_kenzo#2]
The camera does not work if we encrypt the device.

**How to reproduce:**
When setting up your device for the first time, put a start-up lock (pin/password/pattern). 
If not that, go to `Settings -> Security & Location -> Encryption & Credentials -> Encrypt Phone`.

> Camera did work when the device wasn't encrypted.

**Model:**
Redmi Note 3

**Extended Version:**
AospExtended-v5.7-OFFICIAL

**Android Version:**
8.1.0

**Android Security Patch Level:**
5-July-2018

**Build Date:**
Sun, Jul 8 22:32:31 IST 2018

**Comment by ASparkOfFire** [comment]
@ramantehlan Known bug
